// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>)
//  {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import ThemeRegistry from "../common/ui/ThemeRegistry/ThemeRegistry";
import ResponsiveAppBar from "../common/ui/components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Material UI built with nextjs app router and typescript",
  description: "Material UI nextjs example",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>

             <ResponsiveAppBar />

             {children}

        </ThemeRegistry>
      </body>
    </html>
  );
}